<a href="https://colab.research.google.com/github/Swooshnv/ML_Training/blob/main/02_Aggregating_tensors_and_changing_datatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf
import numpy as np

In [3]:
tensor = tf.constant([2, 6])
tensorTwo = tf.constant([2., 6.])
print(f"tensor datatype is {tensor.dtype} \ntensorTwo datatype is {tensorTwo.dtype}")

tensor datatype is <dtype: 'int32'> 
tensorTwo datatype is <dtype: 'float32'>


In [5]:
# Changing datatype using tf.cast
tensorCast = tf.cast(tensor, dtype = tf.int16)
tensorTwoCast = tf.cast(tensorTwo, dtype = tf.float16)
print(f"tensorCast dtype is {tensorCast.dtype} \ntensorTwoCast dtype is {tensorTwoCast.dtype}")

tensorCast dtype is <dtype: 'int16'> 
tensorTwoCast dtype is <dtype: 'float16'>


In [8]:
tensorThree = tf.cast(tensorTwoCast, dtype = tf.int16)
print(f"tensorTwoCast: {tensorTwoCast.numpy()}\ntensorThree: {tensorThree.numpy()}")

tensorTwoCast: [2. 6.]
tensorThree: [2 6]


In [13]:
# Get the absolute of an input
tensor = tf.constant([-2,-7])
print(f"Original tensor: {tensor.numpy()}\nAbsolute tensor: {tf.abs(tensor.numpy())}")

Original tensor: [-2 -7]
Absolute tensor: [2 7]


In [22]:
tensor = tf.constant(np.random.randint(0, 100, size = 50), shape = (5, 2, 5))
print(f"{tensor.numpy()}\nMinimum value of the tensor: {tf.reduce_min(tensor)}\nMaximum value of the tensor: {tf.reduce_max(tensor)}\nMean of the tensor: {tf.reduce_mean(tensor)}\nSum of the tensor: {tf.reduce_sum(tensor)}")

[[[34 79 69 49 39]
  [38  6 42 23 37]]

 [[46 60 60 22 72]
  [15 25 52 23 23]]

 [[84 95 38 86 43]
  [90  5 11 34  6]]

 [[51 25 17 24 24]
  [44 42 72 67 39]]

 [[58 78 77 17 97]
  [70 36 31 92 56]]]
Minimum value of the tensor: 5
Maximum value of the tensor: 97
Mean of the tensor: 46
Sum of the tensor: 2323


In [35]:
import tensorflow_probability as tfp
tensorFlat = tf.reshape(tensor, shape = (50))
print(f"Variance of the tensor: {tfp.stats.variance(tensorFlat)}")

Variance of the tensor: 650


In [40]:
print(f"Standard deviation of the tensor: {tf.math.reduce_std(tf.cast(tensorFlat, dtype = tf.float32))}") # Only works with real/complex inputs

Standard deviation of the tensor: 25.492124557495117


In [45]:
# Indexing the max/min of a tensor
print(tensor.numpy())
print(f"Argmax of the tensor: {tf.math.argmax(tensor)}\nArgmin of the tensor: {tf.math.argmin(tensor)}")
print(tensorFlat.numpy())
print(f"Argmax of the flattened tensor: {tf.math.argmax(tensorFlat)}\nArgmin of the flattened tensor: {tf.math.argmin(tensorFlat)}")

[[[34 79 69 49 39]
  [38  6 42 23 37]]

 [[46 60 60 22 72]
  [15 25 52 23 23]]

 [[84 95 38 86 43]
  [90  5 11 34  6]]

 [[51 25 17 24 24]
  [44 42 72 67 39]]

 [[58 78 77 17 97]
  [70 36 31 92 56]]]
Argmax of the tensor: [[2 2 4 2 4]
 [2 3 3 4 4]]
Argmin of the tensor: [[0 3 3 4 3]
 [1 2 2 0 2]]
[34 79 69 49 39 38  6 42 23 37 46 60 60 22 72 15 25 52 23 23 84 95 38 86
 43 90  5 11 34  6 51 25 17 24 24 44 42 72 67 39 58 78 77 17 97 70 36 31
 92 56]
Argmax of the flattened tensor: 44
Argmin of the flattened tensor: 26


In [57]:
# Squeezing/Unsqueezing a tensor
tensor = tf.random.uniform(shape = (1, 1, 1, 1, 50))
print(f"{tensor.numpy()}\nTensor.ndim: {tensor.ndim}")
print(f"Squeezed tensor.ndim: {tf.squeeze(tensor, axis = 0).ndim}")
print(f"Unsqueezed tensor.ndim: {tf.expand_dims(tensor, axis = 0).ndim}")

[[[[[0.70623434 0.11550748 0.7788601  0.2622193  0.2999668  0.25942016
     0.7712139  0.906829   0.76438904 0.86540794 0.9701414  0.47197628
     0.10267639 0.45918858 0.26038718 0.33747816 0.79310954 0.6949699
     0.607481   0.06066883 0.45438743 0.6322751  0.90195024 0.1920414
     0.38311386 0.08330989 0.8553629  0.7127478  0.306504   0.451787
     0.78712773 0.60103834 0.00271797 0.35027003 0.5642177  0.58296585
     0.31810343 0.16030312 0.7012918  0.01277125 0.86926603 0.5855551
     0.59014356 0.7234719  0.8580897  0.4313029  0.26071906 0.8269534
     0.31711996 0.64558554]]]]]
Tensor.ndim: 5
Squeezed tensor.ndim: 4
Unsqueezed tensor.ndim: 6


In [58]:
# One-hot encoding tensors
list = [0, 1, 2, 3]
tf.one_hot(list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [59]:
tf.one_hot(list, depth = 4, on_value = "Run", off_value = "Hide")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Run', b'Hide', b'Hide', b'Hide'],
       [b'Hide', b'Run', b'Hide', b'Hide'],
       [b'Hide', b'Hide', b'Run', b'Hide'],
       [b'Hide', b'Hide', b'Hide', b'Run']], dtype=object)>

In [67]:
tensor = tf.constant([[4, 3],
                      [7, 1]], dtype = tf.float32)
print(f"{tensor.numpy()}\nSquare of the tensor: {tf.square(tensor)}\nSquare root of the tensor: {tf.sqrt(tensor)}\nLogarithm of the tensor: {tf.math.log(tensor)}")

[[4. 3.]
 [7. 1.]]
Square of the tensor: [[16.  9.]
 [49.  1.]]
Square root of the tensor: [[2.        1.7320508]
 [2.6457512 1.       ]]
Logarithm of the tensor: [[1.3862944 1.0986123]
 [1.9459101 0.       ]]
