<a href="https://colab.research.google.com/github/Swooshnv/ML_Training/blob/main/Tensorflow/00_Basics_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [34]:
scalar = tf.constant(12)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [35]:
scalar.ndim

0

In [36]:
vector = tf.constant([12, 16])
print(vector,vector.ndim)

tf.Tensor([12 16], shape=(2,), dtype=int32) 1


In [37]:
matrix = tf.constant([[15, 2],
          [12,14]])
print(matrix,matrix.ndim)

tf.Tensor(
[[15  2]
 [12 14]], shape=(2, 2), dtype=int32) 2


In [38]:
matrix_2 = tf.constant([[1., 3.],
                        [5., 2.],
                        [8., 9.]], dtype = tf.float16)
print(matrix_2, matrix_2.ndim)

tf.Tensor(
[[1. 3.]
 [5. 2.]
 [8. 9.]], shape=(3, 2), dtype=float16) 2


In [39]:
tensor = tf.constant([[[1, 7], [4, 7]],
                      [[13, 6], [2, 4]]])
print(tensor, tensor.ndim)

tf.Tensor(
[[[ 1  7]
  [ 4  7]]

 [[13  6]
  [ 2  4]]], shape=(2, 2, 2), dtype=int32) 3


In [40]:
tensor = tf.Variable([45, 36])
tensor_2 = tf.constant([13, 7]) # Constant tensors does not support item assignment
tensor, tensor_2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([45, 36], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([13,  7], dtype=int32)>)

In [41]:
tensor[0].assign(15)
tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 36], dtype=int32)>

In [42]:
random = tf.random.Generator.from_seed(42)
random = random.normal(shape = (3, 4))
random 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [43]:
unshuffled = tf.constant([[15, 3],
                          [6, 2],
                          [8, 14]])
unshuffled, unshuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[15,  3],
        [ 6,  2],
        [ 8, 14]], dtype=int32)>, 2)

In [44]:
shuffled = tf.random.shuffle(unshuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  2],
       [ 8, 14],
       [15,  3]], dtype=int32)>

In [46]:
ones = tf.ones(shape = (3, 4))
zeros = tf.zeros(shape = (2, 3))
ones, zeros

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [47]:
import numpy as np
npArray = np.arange(1, 25, dtype = np.int32)
npArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [50]:
cvtArray = tf.constant(npArray)
cvtArrayReshaped = tf.constant(npArray, shape = (2, 3, 4))
cvtArray, cvtArrayReshaped

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [51]:
cvtArray.ndim, cvtArrayReshaped.ndim

(1, 3)

In [56]:
cvtArray.shape, cvtArrayReshaped.shape

(TensorShape([24]), TensorShape([2, 3, 4]))

In [57]:
tf.size(cvtArray), tf.size(cvtArrayReshaped)

(<tf.Tensor: shape=(), dtype=int32, numpy=24>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [60]:
cvtArrayReshaped[0], cvtArrayReshaped[0, 0], cvtArrayReshaped[0, 0, 0]

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [62]:
print(f"Datatype of the elements in the Tenson: {cvtArray.dtype}")
print(f"Number of dimensions: {cvtArray.ndim}")
print(f"Shape of Tensor: {cvtArray.shape}")
print(f"Elements along the first axis: {cvtArray.shape[0]}")
print(f"Elements along the last axis: {cvtArray.shape[-1]}")
print(f"Total number of elements: {tf.size(cvtArray)}")

Datatype of the elements in the Tenson: <dtype: 'int32'>
Number of dimensions: 1
Shape of Tensor: (24,)
Elements along the first axis: 24
Elements along the last axis: 24
Total number of elements: 24
