<a href="https://colab.research.google.com/github/Swooshnv/ML_Training/blob/main/01_Manipulating_and_indexing_tensors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

array = np.arange(0, 50, dtype = np.float32)
Tensor = tf.constant(array, shape = (5, 2, 5), dtype = tf.int32)
array, Tensor

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       dtype=float32), <tf.Tensor: shape=(5, 2, 5), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],
 
        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],
 
        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]], dtype=int32)>)

In [2]:
# Getting the first two elements of each dimension
Tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 5,  6]],

       [[10, 11],
        [15, 16]]], dtype=int32)>

In [3]:
Tensor_2 = tf.constant([[[3, 5], [6, 2]],
                        [[7, 1], [2, 9]],
                        [[9, 1], [6, 6]]])
Tensor_2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[3, 5],
        [6, 2]],

       [[7, 1],
        [2, 9]],

       [[9, 1],
        [6, 6]]], dtype=int32)>

In [4]:
# Last item of each row of tensor
Tensor_2[::, -1, -1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 9, 6], dtype=int32)>

In [5]:
# Ranking up a tensor
reshapedTensor = tf.constant(Tensor_2, shape = (1, 3, 2, 2))
Tensor_2.ndim, reshapedTensor.ndim
reshapedTensor

<tf.Tensor: shape=(1, 3, 2, 2), dtype=int32, numpy=
array([[[[3, 5],
         [6, 2]],

        [[7, 1],
         [2, 9]],

        [[9, 1],
         [6, 6]]]], dtype=int32)>

In [6]:
# In another way
reshaped = Tensor_2[..., tf.newaxis]
reshaped, reshaped.shape

(<tf.Tensor: shape=(3, 2, 2, 1), dtype=int32, numpy=
 array([[[[3],
          [5]],
 
         [[6],
          [2]]],
 
 
        [[[7],
          [1]],
 
         [[2],
          [9]]],
 
 
        [[[9],
          [1]],
 
         [[6],
          [6]]]], dtype=int32)>, TensorShape([3, 2, 2, 1]))

In [7]:
expandedTensor = tf.expand_dims(Tensor_2, axis = -1)
expandedTensor, expandedTensor.shape

(<tf.Tensor: shape=(3, 2, 2, 1), dtype=int32, numpy=
 array([[[[3],
          [5]],
 
         [[6],
          [2]]],
 
 
        [[[7],
          [1]],
 
         [[2],
          [9]]],
 
 
        [[[9],
          [1]],
 
         [[6],
          [6]]]], dtype=int32)>, TensorShape([3, 2, 2, 1]))

In [8]:
tensor = tf.constant([[4, 6],
                      [17, 3]])
tensor, tensor * 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 4,  6],
        [17,  3]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 40,  60],
        [170,  30]], dtype=int32)>)

In [9]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 16],
       [27, 13]], dtype=int32)>

In [10]:
tensor -= 1
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  5],
       [16,  2]], dtype=int32)>

In [11]:
result = tf.multiply(tensor, 5)
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 25],
       [80, 10]], dtype=int32)>

In [12]:
result = tf.add(tensor, 150)
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[153, 155],
       [166, 152]], dtype=int32)>

In [14]:
matrix = tf.constant([[4, 5],
                      [7, 2]])
matrixTwo = tf.constant([[5, 1],
                        [9, 7]])
matrix, matrixTwo

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [7, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 1],
        [9, 7]], dtype=int32)>)

In [18]:
# Multiplication of matrices
print(f"Using tf.matmul: {tf.matmul(matrix, matrixTwo).numpy()}")
# Same as above but with python command
print(f"Using \"@\" Command:  {matrix @ matrixTwo}")

Using tf.matmul: [[65 39]
 [53 21]]
Using "@" Command:  [[65 39]
 [53 21]]


In [19]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
tensorTwo = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

In [24]:
reshaped = tf.reshape(tensorTwo, shape = (3, 2))
print(tensor.numpy())
print(reshaped.numpy())
print(f"Dot product of the tensors: {tf.matmul(tensor, reshaped)}")

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
Dot product of the tensors: [[22 28]
 [49 64]]


In [25]:
transposed = tf.transpose(tensorTwo)
print(tensor.numpy())
print(transposed.numpy())
print(f"Dot product of the tensors: {tf.matmul(tensor, transposed)}")

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
Dot product of the tensors: [[14 32]
 [32 77]]
